# Generated by Django 2.2.3 on 2019-07-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ClassRoom'),
        ),
    ]
