# Generated by Django 2.2.3 on 2019-07-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190722_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_room',
        ),
    ]
